### ISSUE TITLE
Trotter step not implemented?

### ISSUE THREAD

**Issue by christopherkang** [microsoft/QuantumLibraries#139]
**Describe the bug**
Trotterization is not implemented within the TrotterStepOracle method. 
I was looking through the implementation of the TrotterStepOracle and saw the reference to the TrotterSimulationAlgorithm method:

https://github.com/microsoft/QuantumLibraries/blob/0da4601378d6bca4dc28fab863f656fce9ecddae/Chemistry/src/Runtime/JordanWigner/Convenience.qs#L34-L35

When we look at the implementation of the TrotterSimulationAlgorithm itself:

https://github.com/microsoft/QuantumLibraries/blob/e6885b1949f485c669a7eeebb2bd878af29d796c/Standard/src/Simulation/Algorithms.qs#L116-L119

Which calls the TrotterSimulationAlgorithmImpl:

https://github.com/microsoft/QuantumLibraries/blob/e6885b1949f485c669a7eeebb2bd878af29d796c/Standard/src/Simulation/Algorithms.qs#L85-L101

So, don't we feed both `trotterStepSize` to both the `trotterStepSize` and `maxTime`, causing the number of time slices to be 1, regardless of the step size? 

This also causes errors in the energy estimate, as the `rescaleFactor` assumes that the Trotterization step has been fully implemented. For example, test the MolecularHydrogen sample with a very small trotterStep. The expected energy balloons or varies wildly.  

**Expected behavior**
The TrotterStepOracle should either apply multiple rounds of small exponentiated matrices or give a warning that Trotterization hasn't been implemented yet. 

**System information**
 - macOS Mojave
 - Microsoft.Quantum.Chemistry 0.7.1905.3109

**Comment by guanghaolow** [comment]
It is currently intended that the TrotterStepOracle for chemistry always applies only one step.

The described interaction with Phase Estimation (PE) is expected. PE provides an estimate of phase with a standard deviation `X` from the true phase that is controlled by bits of precision. 

As the phase of a Trotter step is approximately the `energy * trotterStepSize`, the standard deviation of the energy estimate is `X / trotterStepSize`. In order to maintain a constant PE standard deviation, one should thus scale the `X` with the step size.

**Comment by christopherkang** [comment]
@guanghaolow Could the docs be updated to reflect this? The [current docs](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.chemistry.jordanwigner.trottersteporacle?view=qsharp-preview) don't mention that the rescale factor needs to be applied in order to obtain the true energy estimate. Also, the oracle returned could be naively thought to apply all trotter steps.
