### ISSUE TITLE
Add function to compare arrays

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumLibraries#225]
**Is your feature request related to a problem? Please describe.**
I'm trying to compare two arrays to see whether they are equal.

**Describe the solution you'd like**
A library function that would compare them for me (for example, `EqualA` in `Microsoft.Quantum.Logical` namespace, to match the pattern of `EqualXXX` in that library).

**Describe alternatives you've considered**
The best solution I could come up with is 

    function EqualA<'T>(array1 : 'T[], array2 : 'T[], equal : (('T, 'T) -> Bool)) : Bool {
        if (Length(array1) != Length(array2)) {
            return false;
        }
        return All(equal, Zip(array1, array2));
    }

Let me know if it would be helpful to send this as a pull request!

**Comment by cgranade** [comment]
Thanks for the feature request. I've generally used the `All(Equal★, Zip(left, right))` idiom, as you note, but that doesn't compare the lengths as your proposal does, so that equality is only compared on the common prefix of both arrays. With respect to the equality function input, it'd be somewhat less awkward if we could apply the `=` operator between values of type `'T`, but in lieu of that I agree that taking a definition of equality as an input makes sense.

As for API design, I'd suggest that the `equal` input should appear first for consistency with `All`, `Mapped`, and other such functions. Other than that, I think this is a good candidate for a PR and API review. Thanks!
