### ISSUE TITLE
Replacing items in a list

### ISSUE THREAD

**Issue by mridulsar** [microsoft/QuantumLibraries#258]
**Describe the bug**
I am using the Q# environment. I am trying to replace an element in a array with another element. Specifically a qubit for another qubit. 

**To Reproduce**
1. Open .qs file
2. Create a set of qubits
3. try accessing the qubits by using brackets s.t. qubits[i] = x
4. Error: Invalid symbol declaration. Expecting either a single symbol or a symbol tuple

**Expected behavior**
I expected to replace the qubit.

**Screenshots**

**System information**
Windows, Python 3.7.7 64bit, VSCode

**Additional context**

**Comment by cgranade** [comment]
Thanks for your question, @mridulsar! Like all other data types in Q#, arrays are immutable values; that in particular means that you cannot change a single element in an array to have a different value. Rather, you can use [update-and-reassign statements](https://docs.microsoft.com/quantum/user-guide/using-qsharp/variables#update-and-reassign-statements) together with the [`w/` operator](https://docs.microsoft.com/quantum/user-guide/language/expressions#copy-and-update-expressions) to achieve the same effect in an immutable fashion.

For example:

```Q#
mutable xs = [0, 1, 2];
set xs w/= 1 <- 10;
Message($"{xs}"); // prints [0, 10, 2]
```

As with other update-and-reassign statements, `w/=` is equivalent to a `set` statement and a use of the `w/` operator, so that the above could also be written more explicitly as:


```Q#
mutable xs = [0, 1, 2];
set xs = xs w/ 1 <- 10;
Message($"{xs}"); // prints [0, 10, 2]
```

For more details, I suggest checking out the following blog posts:
- https://devblogs.microsoft.com/qsharp/qsharp-06-language-features-and-more/#mutability
- https://dev.to/crazy4pi314/an-array-of-facts-on-arrays-in-q-50m2

If you have more questions, we're happy to help. I'd also suggest that https://quantumcomputing.stackexchange.com/ is a great resource for asking questions about developing quantum applications with Q#.

**Comment by mridulsar** [comment]
This helps me quite a bit! Thank you!

**Comment by cgranade** [comment]
No worries, @mridulsar, happy to help!
