### ISSUE TITLE
`ControlledOnBitString` behavior when bitstring and control register are not the same length not documented

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/QuantumLibraries#262]
**Describe the bug**
This _may_ not be a bug, but I wanted to capture that the behavior for `ControlledOnBitString` is not clear when the control register it is applied to is longer than the control bitstring (the first argument) itself.
(ControlledOnBitString(address, ApplyPauliFromBitString(PauliX, true, _, _)))
            (addressRegister!, (values, targetRegister));
**To Reproduce**
See [gist](https://gist.github.com/crazy4pi314/516936ac7777660d2694eb9d7f957263) here, run the sample in binder: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/crazy4pi314/516936ac7777660d2694eb9d7f957263/master)

```qsharp
open Microsoft.Quantum.Diagnostics;

operation ControllingStringCorrectLength() : Unit {
    let address = [true, false, true];
    using((addressRegister, target) = (Qubit[3], Qubit())){
        // Prepare address register to address value
        ApplyPauliFromBitString(PauliX, true, address, addressRegister);
        // Control on the same address, should put target qubit in superposition.
        (ControlledOnBitString(address, H))
            (addressRegister, target);
        DumpMachine();
        ResetAll(addressRegister+[target]);
    }
}

operation ControllingStringShort() : Unit {
    let address = [true, false];
    using((addressRegister, target) = (Qubit[3], Qubit())){
        // Prepare address register to address value
        ApplyPauliFromBitString(PauliX, true, address, addressRegister);
        // Control on the same address, should put target qubit in superposition.
        (ControlledOnBitString(address, H))
            (addressRegister, target);
        DumpMachine();
        ResetAll(addressRegister+[target]);
    }
}

```

**Expected behavior**
I guess I am not sure what I should expect in this case? That is part of why I am filing this :P 

**Screenshots**
Screenshot of the attached 
![image](https://user-images.githubusercontent.com/6486256/84332367-9ccb1400-ab41-11ea-9235-7a40d5de8223.png)

**System information**
 - OS: Windows 10
![image](https://user-images.githubusercontent.com/6486256/84332457-d734b100-ab41-11ea-958e-3be0b299a64b.png)

**Comment by cgranade** [comment]
Thanks for the report, and for the reproduction, I really appreciate having the minimal working example of the issue! In any case, the issue is at the very least a problem of the documentation not being more clear. Given that, I can see four distinct resolutions:

- Keep the current behaivor of `ControlledOnBitString`, but clarify in the API documentation.
- Make `ControlledOnBitString` pad the control array on the right by zeros instead of ones, bringing `ControlledOnBitString` in line with the little-endian representation used elsewhere. This would be a breaking change.
- Make `ControlledOnBitString` not control on qubits past the length of the control pattern. This would be a breaking change.
- Make `ControlledOnBitString` `fail` when the control pattern and register are of different lengths. This would be a breaking change.

I'm personally partial to the second option, myself, as that would have the interpretation of leaving qubits without a control pattern uncontrolled, but I'd love to get other input before deciding on that. Any thoughts, @msoeken?

**Comment by msoeken** [comment]
@cgranade, I don't completely understand when you say

> as that would have the interpretation of leaving qubits without a control pattern uncontrolled.

Wouldn't they be controlled on `false` with the second option, but uncontrolled with the third option? If we accept a breaking change, then I'd favour the third option and always take as length the length of the shortest array, similar to many implementations of `zip`.

**Comment by cgranade** [comment]
Sorry @msoeken, I apparently can't count. Yes, the third option, you're quite right. In any case, I think that even though that would be a breaking change, it would be the most consistent with my expectation from Zip and other functions, as you say.
