### ISSUE TITLE
Add ApplyUnitaryOperation(unitary: Complex[][], qubits : LittleEndian)

### ISSUE THREAD

**Issue by amirebrahimi** [microsoft/QuantumLibraries#291]
This came up in discussion on the [Q# community gitter](https://gitter.im/qsharp-community/community) and I'm mainly logging this, so I don't forget. Ideally, I'd like to implement this myself as I learn more about Q# and quantum computing in general. If anyone has good resources towards implementing this, then please add a comment.

**Is your feature request related to a problem? Please describe.**
In other quantum frameworks it's possibly to apply an arbitrary unitary, but this doesn't currently exist in Q#, so it'd be nice to have.

**Describe the solution you'd like**
Add a method to the API: `ApplyUnitaryOperation(unitary: Complex[][], qubits : LittleEndian)` similar to [`PrepareArbitraryState`](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.preparation.preparearbitrarystate).

**Describe alternatives you've considered**
I suppose it might be possible to use other frameworks to convert a unitary to gate operations and then move those over to Q#, but this would be a better dev experience.

**Additional context**
Original [gitter conversation](https://gitter.im/qsharp-community/community?at=5ee6afd8013105125a35fd4d).

**Comment by amirebrahimi** [comment]
One resource I found (KAK method): https://qiskit.org/documentation/_modules/qiskit/quantum_info/synthesis/two_qubit_decompose.html

**Comment by fedimser** [comment]
Hi! Recently I have implemented an algorithm which deomposes unitary matrix into Q# gates: https://github.com/fedimser/quantum_decomp
It's based on two-level decomposition algorithm, and for case of 4x4 unitary it can do something very similar to KAK method.
It is written in Python and doesn't use any library except NumPy. 

Would it make sense to port it to Microsoft QuantumLibraries repository? What would be the best way to do this?

**Comment by msoeken** [comment]
Hi @fedimser, your project looks very interesting! Thanks for suggesting it here. It would fit into the Microsoft.Quantum.Synthesis namespace. However, to keep the dependencies of the Q# standard libraries low, the code should be rewritten in a way that a Q# operation can be directly called (instead of it being generated). The implementation can make use of intrinsics that can be written in C# (instead of Python).

I'd also like to get the opinions from my colleagues @guenp and @cgranade on this.

**Comment by cgranade** [comment]
@fedimser: Thanks for sharing, that looks quite neat! I concur with @msoeken that, in order to be usable from other Q# code directly, the feature would need to be ported to Q# before we could include it in the Q# standard library as a contribution. If you're interested in doing so, I'm happy to help offer advice and/or feedback, and to help figure out if there's any missing features on the QDK side that could make things easier.

In the meantime, one neat way to share your decomposition project may be to reach out to the qsharp.community group that @amirebrahimi mentioned above. I believe they're now using Slack instead of Gitter, such that you can join at https://join.slack.com/t/qsharp-community/shared_invite/zt-fnsl4u42-u21wdJRzlLF9oAqYTDDtwA. Thanks again for sharing this neat example!

**Comment by guenp** [comment]
@msoeken thanks for tagging me! I think it will be really valuable to add this to the QDK, I personally think having the Python implementation will be very useful for our Python users. Additionally, I can see the value in having a .NET based implementation, either in C# or Q#. Thank you @fedimser for sharing this work.

**Comment by fedimser** [comment]
Hi @msoeken,
Thanks for your reply, I am going now to implement this algorithm in Q# and C# in Microsoft.Quantum.Synthesis.

This is how I plan to do it:
1. Implement Q# operation which implements single-qubit gate given by 2x2 unitary matrix (using ZYZ decomposition).
2. Write algorithm in C# which takes 2^n x 2^n matrix and decomposes it into sequence of fully-controlled 2x2 gates and single-qubit X gates.
3. Implement `ApplyUnitaryOperation(unitary: Complex[][], qubits : LittleEndian)` which first calls algorithm (2) (as intrinsic), and then replaces every fully-controlled gate by call to operation (1) with `Controlled` functor.

I think this is more effective than my Python implementation, because it won't explicitly make every individual Ry,Ry,R1 qubit fully controlled, and let Q# to take care of that.

I will send a pull request when ready. 

@cgranade, thanks for your offer to help with advice, i will contact you if I will get stuck.

Also, I am not going to implement KAK decomposition in first PR, but we can do it as a follow-up as improvement to algorithm (2). It will reduce number of resulting elementary gates, but only for 4x4 case.

**Comment by msoeken** [comment]
This issue has been recently addressed by #391.
