### ISSUE TITLE
AllowAtMostNCallsCA requires restricted operation to have adjoint and controlled

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumLibraries#343]
**Describe the bug**
`AllowAtMostNCallsCA` requires its operation parameter to have adjoint and controlled variants defined, so it can't be used with measurements or any operations returning values (or just operations which don't have these variants). The `'TOutput` in the parameter signature `op : ('TInput => 'TOutput is Adj + Ctl)` seems to imply that using `AllowAtMostNCallsCA` should be possible with operations that return something other than `Unit`, and a lot of use cases for this functionality involves such operations.

**To Reproduce**
The following code does not compile:
```qsharp
within {
    AllowAtMostNCallsCA(0, M, "Too many calls to M.");
} apply {
    // Apply the operation
    op(qs);
}
```

**Expected behavior**
The code compiles and prohibits the operation `op` to use measurements.

**System information**
 - QDK 0.12.20100504

**Comment by tcNickolas** [comment]
@cgranade @msoeken How tricky to fix is this issue? At a glance I couldn't figure out how the implementation of AllowAtMostNCallsCA uses the adjoint or controlled variants of the restricted operation, so maybe they are not essential? (I also noticed that the operation itself has suffix `CA` but is only adjointable.)

For a bit of context, I'm looking into the tasks for an event we have in April, and being able to use AllowAtMostNCallsCA with ToffoliSimulator to prohibit measurements would simplify their implementation a lot.

**Comment by cgranade** [comment]
Thanks for your patience, @tcNikolas; last week was a little bit hectic on my end...! In any case, I agree with you and @msoeken that we can likely relax the requirement that the operation being counted is adjointable and controllable— what's critical is that the allowance operation itself is adjointable so that it can be used in a `within` block. Given that, I would propose that @msoeken's option 2 from #431 be adopted (deprecate `AllowAtMostNCallsCA` in favor of a new `AllowAtMostNCalls` that is adjointable but not controllable, and that does not require its input to be adjointable or controllable). Since this blocks an upcoming event, I'm happy to in the meantime approve #431 and to add @msoeken's option 2 to April API review scheduling. 

That is formally an API change, but it's small enough, blocks something time sensitive, and is nonbreaking such that I'm happy to approve #431 as an exception to our normal process if @msoeken and @guenp agree from the API review board perspective.

**Comment by tcNickolas** [comment]
#431 works great for me (assuming it allows to prohibit using measurements - I haven't verified that, but it looks like it will), the name is a minor issue that definitely is not blocking for me!
