### ISSUE TITLE
Partitioned creates an extra zero-length partition if partitioning is exact

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumLibraries#346]
**Describe the bug**
If I provide [Partitioned](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.partitioned) an array of length N and partition sizes of total length N, the return contains an extra partition of length 0 in the end. This makes it inconvenient to use: if I want to split an array into K parts of equal length ([example](https://github.com/microsoft/QuantumKatas/blob/ddc5d86742fffb09afc7e08d931d33c1be2c4870/GraphColoring/ReferenceImplementation.qs#L45)), I need to remember to ask for K-1 partitions. This behavior is also not documented in API docs, so I don't think it's intended.

**To Reproduce**
The following code:
```qsharp
    let p = Partitioned([2, 2], [1, 2, 3, 4]);
    Message($"{p}");
```
outputs `[[1,2],[3,4],[]]`.

**Expected behavior**
I would expect `[[1,2],[3,4]]`, without the extra empty partition.

**Comment by msoeken** [comment]
Not complete sure whether this is intended, since the documentation stays that the last array will contain the remaining elements. In the example, there are no remaining elements, hence the last array is empty. Would like to hear @cgranade's interpretation as well. In any case, we should the documentation more clear and add further examples.

I understand that the example serves to illustrate this issue, but to split an array into partitions of equal length, `Chunks` would be a more suitable function.

**Comment by cgranade** [comment]
As @msoeken notes, this behavior is intended and is what discriminates `Partitioned` from `Chunks`. In particular, the thought is that `Tail(Partitioned(...))` should always return the "leftover" elements, while `Most(partitioned))` should always return the complete partitions of the array. Agreed, though, we can improve the API documentation to make this more explicit. We could also consider in the future modifying `Partitioned` to return `('T[][], 'T[])` to more clearly separate the "leftover" elements.
