### ISSUE TITLE
Consistency between ApplyIf operations for Result and Bool variants

### ISSUE THREAD

**Issue by msoeken** [microsoft/QuantumLibraries#377]
**Is your feature request related to a problem? Please describe.**
Improve the consistency of library API. Currently
* `ApplyIf{,A,C,CA}` take `op`, `value`, `args`, whereas
* `ApplyIfElse{B,R}{,A,C,CA}` and `ApplyIf{One,Zero}` take `value`, `ops`, `args`

**Describe the solution you'd like**
Modify the order of arguments in `ApplyIf{,A,C,CA}`

**Describe alternatives you've considered**
Modify the order of arguments in the other operations. 

**Additional context**
The suggested solutions change API and cannot make use of deprecation, because operation names and namespaces are not changed.

**Comment by cgranade** [comment]
Thanks for raising this, @msoeken, it would be good to resolve this! One thing we may run into is that the runtime currently has a dependency on these operations, such that there is possibly some impact there; @swernli may know more on that point. In any case, let's put a proposal together and get this onto the December API review.

**Comment by cgranade** [comment]
@swernli: Circling back on this one, do you know if it would break anything in the QIR pipeline or the runtime to modify `ApplyIf{,A,C,CA}` to be consistent with `ApplyIfElse{B,R}{,A,C,CA}` and `ApplyIf{One,Zero}`?

**Comment by swernli** [comment]
@cgranade Actually, the runtime does not use these versions of `ApplyIf*` anywhere in favor of defining it's own. Unifying the library versions and the runtime versions is going to be a hard problem that we need to chat about at some point, but for now these library callables are a convenience that no infrastructure in compiler or runtime depends on.

**Comment by cgranade** [comment]
@swernli: That definitely makes things a lot easier, then! @msoeken, would you be willing to write this up as a proposal, then, so that we can get the various ApplyIf* operations aligned with each other? Thank you!

**Comment by cgranade** [comment]
## Proposal

### New and modified functions, operations, and UDTs

```
operation ApplyIf<'T>(value : Bool, op : ('T => Unit), args : 'T) : Unit { ... }
operation ApplyIfA<'T>(value : Bool, op : ('T => Unit is Adj), args : 'T) : Unit is Adj { ... }
operation ApplyIfC<'T>(value : Bool, op : ('T => Unit is Ctl), args : 'T) : Unit is Ctl { ... }
operation ApplyIfCA<'T>(value : Bool, op : ('T => Unit is Adj + Ctl), args : 'T) : Unit is Adj + Ctl { ... }
```

### Impact of breaking changes

Since this proposal suggests changing the order of inputs on existing operations without changing the name of those operations, implementing this proposal necessarily requires making breaking changes to the Q# standard library API. Users of the existing `ApplyIf{,A,C,CA}` callables will require modifications to their code.

**Comment by cgranade** [comment]
Looks like I forgot to remove the "needs API review" label when this was approved. In any case, @msoeken  do you want to handle this, or should I? As a side note, since this is necessarily a breaking change (reordering inputs cannot be handled with deprecation stubs), we should coordinate with @efratshabtai to make sure to land this when we have other breaking changes at the same time.

**Comment by msoeken** [comment]
@cgranade, I can handle this.

**Comment by cgranade** [comment]
Much obliged, @msoeken!
