### ISSUE TITLE
A Timeout Behavior When Using the Chunks Function 

### ISSUE THREAD

**Issue by weucode** [microsoft/QuantumLibraries#538]
# Description

When running the following Q# program,a timeout behavior occurred,and the execution time is over 2 minutes.I guess the special value(0) of the first parameter in `Chunks` results in it.Is my guess right?Looking forward to your reply. Thank you!

# Testcase

```c#
namespace NISLNameSpace {
	open Microsoft.Quantum.Arrays;

	@EntryPoint()
	operation main() : Unit {
		mutable NISLParameter0 = 0;
		mutable NISLParameter1 = [1,2,3];
		mutable result = Chunks(NISLParameter0,NISLParameter1);
	}
}
```

# Behavior

Timeout (runs for more than 2 minutes)

# Environment

`operating system:`Windows 10

`dotnet version:`5.0.301

`QDK:`v0.23.195983

**Comment by tcNickolas** [comment]
@weucode Thank you for the report!

@msoeken Looks like we need to add a check to https://github.com/microsoft/QuantumLibraries/blob/252613ad4080244b2202aebd5422892b59eca316/Standard/src/Arrays/Arrays.qs#L296 to make sure `nElements > 0`, otherwise it's stuck producing empty chunks. It wouldn't even be a breaking change, since the behavior for `nElements <= 0` was broken anyways. Let me know if I can help with this!

**Comment by msoeken** [comment]
Thanks @weucode for raising this. @tcNickolas, thanks, feel free to address this issue.
